# Generated by Django 4.2.2 on 2023-07-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentContact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.IntegerField(max_length=4),
        ),
    ]
