# Generated by Django 4.2.2 on 2023-07-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_studentdep_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='studentdep',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentdep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department'),
        ),
    ]
