# Generated by Django 4.2.2 on 2023-07-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_department_studentdep_alter_student_studentdep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentdep',
            new_name='studentDepartment',
        ),
    ]
