# Generated by Django 4.2.2 on 2023-07-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_studentdep_student_studentdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='studentdep',
            new_name='studentDepartment',
        ),
    ]
