# Generated by Django 4.2.2 on 2023-07-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_studentdep_department_studentdepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentDepartment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
